track_thresh: 0.1  # tracking confidence threshold, should be the same as model conf
track_buffer: 30   # the frames for keeping lost tracks
match_thresh: 0.5  # matching threshold for tracking
frame_rate: 30     # FPS
conf_thres: 0.5122620708221085
